/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simplest.possible.implementation;

import java.util.Collections;
import java.util.List;

public class PrimeFactors {
    public boolean someLibraryMethod() {
        return true;
    }

    public List<Object> checkFactors(int Number){
        if (Number==1){
            return Collections.emptyList();
        }
        return null;
    }
}
